{"level":"error","message":"Exception is not defined","timestamp":"2018-10-06T23:51:53.966Z"}
{"level":"error","message":"erro reject promise","timestamp":"2018-10-06T23:52:55.005Z"}
{"level":"error","message":"erro reject promise","timestamp":"2018-10-06T23:55:13.945Z"}
{"message":"failed to reconnect after 30 attempts with interval 1000 ms 07-10-2018 13:50:33","name":"MongoNetworkError","stack":"MongoNetworkError: failed to reconnect after 30 attempts with interval 1000 ms\n    at Connection.<anonymous> (C:\\Users\\allan\\Desktop\\Allan\\node_exemples\\8.7-Project\\8.7- Project\\after\\vidly\\node_modules\\mongodb-core\\lib\\connection\\pool.js:373:13)\n    at Connection.emit (events.js:182:13)\n    at Socket.<anonymous> (C:\\Users\\allan\\Desktop\\Allan\\node_exemples\\8.7-Project\\8.7- Project\\after\\vidly\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\nFrom previous event:\n    at Object.promiseOrCallback (C:\\Users\\allan\\Desktop\\Allan\\node_exemples\\8.7-Project\\8.7- Project\\after\\vidly\\node_modules\\mongoose\\lib\\utils.js:221:10)\n    at model.Query.exec (C:\\Users\\allan\\Desktop\\Allan\\node_exemples\\8.7-Project\\8.7- Project\\after\\vidly\\node_modules\\mongoose\\lib\\query.js:2948:16)\n    at model.Query.Query.then (C:\\Users\\allan\\Desktop\\Allan\\node_exemples\\8.7-Project\\8.7- Project\\after\\vidly\\node_modules\\mongoose\\lib\\query.js:2975:15)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","__stackCleaned__":true,"level":"error","timestamp":"2018-10-07T16:52:35.373Z"}
